### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [dorotawm/oop-put-course#1]
**Task 1**
- [x] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Put all code in one repo instead of two

**Task 2**
- [x] Format code

**Comment by dorotawm** [comment]
@jakub-hamerlinski-put I have a question about point "Put all code in one repo instead of two" -> do you mean there should be separate folders in this repo for each task or should I just improve the code created for 1st task by adding code that meets the requirements of 2nd task?
